config/routes.rb
Rails.application.routes.draw do
  resources :amvs
  resources :amvs_amvs
  resources :amvs_jvs
  resources :amvs_animes
  resources :amvs_groupes
  resources :amvs_conventions
  resources :amvs_types
  resources :amvs_makers
  resources :volumes_mangas
  resources :volumes
  resources :volumes_illustrations
  resources :volumes_types
  resources :volumes_lns
  resources :videos
  resources :videos_id_cats
  resources :tablatures
  resources :tablatures_people
  resources :sites_dachats
  resources :sites_dachats_pays
  resources :restaurants
  resources :restaurants_pays
  resources :recettes
  resources :recettes_difficultes
  resources :recettes_plats
  resources :recettes_types
  resources :petites_annonces
  resources :petites_annonces_lieus
  resources :petites_annonces_pays
  resources :petites_annonces_sections
  resources :personnalites
  resources :personnalites_people_plus
  resources :personnalites_people
  resources :personnalites_id_travauxes
  resources :personnalites_id_galeries
  resources :personnalites_ex_fins
  resources :personnalites_ex_debuts
  resources :personnalites_exes
  resources :personnalites_id_membres
  resources :personnalites_roles
  resources :personnalites_agences_exes
  resources :personnalites_agences_fins
  resources :personnalites_agences_debuts
  resources :personnalites_agences
  resources :personnalites_labels_exes
  resources :personnalites_labels_fins
  resources :personnalites_labels_debuts
  resources :personnalites_labels
  resources :personnalites_genres
  resources :personnalites_statuts
  resources :personnalites_pays
  resources :personnalites_sexes
  resources :personnalites_type_people
  resources :personnage_de_mangas
  resources :personnage_de_mangas_goodies
  resources :personnage_de_mangas_jv_persos
  resources :personnage_de_mangas_perso_plus
  resources :personnage_de_mangas_persos
  resources :personnage_de_mangas_perso_mangas
  resources :personnage_de_mangas_mangas
  resources :personnages_de_jeux_videos
  resources :personnages_de_jeux_videos_goodies
  resources :personnages_de_jeux_videos_perso_mangas
  resources :personnages_de_jeux_videos_perso_plus
  resources :personnages_de_jeux_videos_persos
  resources :personnages_de_jeux_videos_jv_persos
  resources :personnages_de_jeux_videos_doubleur_roles
  resources :personnages_de_jeux_videos_doubleur_people
  resources :personnages_de_jeux_videos_doubleur_pays
  resources :personnages_de_jeux_videos_jvs
  resources :personnage_danimes
  resources :personnage_danimes_goodies
  resources :personnage_danimes_jv_persos
  resources :personnage_danimes_perso_mangas
  resources :personnage_danimes_perso_plus
  resources :personnage_danimes_persos
  resources :personnage_danimes_doubleur_roles
  resources :personnage_danimes_doubleur_people
  resources :personnage_danimes_doubleur_pays
  resources :personnage_danimes_animes
  resources :personnage_danimes_sexes
  resources :paroles
  resources :paroles_paroles
  resources :paroles_staff_people
  resources :paroles_staff_roles
  resources :numero_demission_tvs
  resources :numero_demission_tvs_clips
  resources :numero_demission_tvs_emission_tv_numeros
  resources :numero_demission_tvs_people
  resources :numero_demission_tvs_presentateurs
  resources :numero_demission_tvs_specials
  resources :numero_demission_tvs_id_emission_tvs
  get "/planning/manga", to: "mangas#planning"
  resources :mangas do
    collection do
      get "planning"
    end
  end
  resources :mangas_clips
  resources :mangas_people
  resources :mangas_concours
  resources :mangas_quizzs
  resources :mangas_sondages
  resources :mangas_actualite_minis
  resources :mangas_cultures
  resources :mangas_actualites
  resources :mangas_artbooks
  resources :mangas_litterature_asiatique_plus
  resources :mangas_litterature_asiatiques
  resources :mangas_am_plus
  resources :mangas_ams
  resources :mangas_jv_plus
  resources :mangas_jvs
  resources :mangas_drama_plus
  resources :mangas_dramas
  resources :mangas_manga_plus
  resources :mangas_mangas
  resources :mangas_ln_plus
  resources :mangas_lns
  resources :mangas_anime_plus
  resources :mangas_animes
  resources :mangas_groupes
  resources :mangas_commerces
  resources :mangas_public_avertis
  resources :mangas_societe_people
  resources :mangas_societe_roles
  resources :mangas_staff_people
  resources :mangas_staff_roles
  resources :mangas_prepublies
  resources :mangas_editeurs_vf_collections
  resources :mangas_editeurs_vfs
  resources :mangas_editeurs_vos
  resources :mangas_encours_vfs
  resources :mangas_encours_vos
  resources :mangas_themes
  resources :mangas_genres
  resources :mangas_types
  resources :mangas_pays
  resources :livres
  resources :livres_jv_plus
  resources :livres_jvs
  resources :livres_people
  resources :livres_actualite_minis
  resources :livres_cultures
  resources :livres_actualites
  resources :livres_goodies
  resources :livres_litterature_asiatique_plus
  resources :livres_litterature_asiatiques
  resources :livres_am_plus
  resources :livres_ams
  resources :livres_drama_plus
  resources :livres_dramas
  resources :livres_manga_plus
  resources :livres_mangas
  resources :livres_ln_plus
  resources :livres_lns
  resources :livres_anime_plus
  resources :livres_animes
  resources :livres_groupes
  resources :livres_public_avertis
  resources :livres_pays_themes
  resources :livres_themes
  resources :livres_genres
  resources :livres_editeurs_vfs
  resources :livres_editeurs_vos
  resources :livres_staff_people
  resources :livres_staff_roles
  resources :livres_statut_publications
  resources :livres_pays
  resources :livres_type_secondaires
  resources :livres_types
  resources :light_novels
  resources :light_novels_quizzs
  resources :light_novels_actualite_minis
  resources :light_novels_cultures
  resources :light_novels_actualites
  resources :light_novels_artbooks
  resources :light_novels_osts
  resources :light_novels_litterature_asiatique_plus
  resources :light_novels_litterature_asiatiques
  resources :light_novels_am_plus
  resources :light_novels_ams
  resources :light_novels_jv_plus
  resources :light_novels_jvs
  resources :light_novels_drama_plus
  resources :light_novels_dramas
  resources :light_novels_ln_plus
  resources :light_novels_lns
  resources :light_novels_manga_plus
  resources :light_novels_mangas
  resources :light_novels_anime_plus
  resources :light_novels_animes
  resources :light_novels_groupes
  resources :light_novels_commerces
  resources :light_novels_public_avertis
  resources :light_novels_societe_people
  resources :light_novels_societe_roles
  resources :light_novels_staff_people
  resources :light_novels_staff_roles
  resources :light_novels_prepublies
  resources :light_novels_editeurs_vf_collections
  resources :light_novels_editeurs_vfs
  resources :light_novels_editeurs_vos
  resources :light_novels_encours_vfs
  resources :light_novels_encours_vos
  resources :light_novels_themes
  resources :light_novels_genres
  resources :light_novels_pays
  resources :jeux_videos, path:"jeuxvideo"
  resources :jeux_videos_topics
  resources :jeux_videos_people
  resources :jeux_videos_concours
  resources :jeux_videos_quizzs
  resources :jeux_videos_sondages
  resources :jeux_videos_amvs
  resources :jeux_videos_doujins
  resources :jeux_videos_cds
  resources :jeux_videos_osts
  resources :jeux_videos_cultures
  resources :jeux_videos_litterature_asiatique_plus
  resources :jeux_videos_litterature_asiatiques
  resources :jeux_videos_artbooks
  resources :jeux_videos_dvds
  resources :jeux_videos_univers
  resources :jeux_videos_drama_plus
  resources :jeux_videos_dramas
  resources :jeux_videos_am_plus
  resources :jeux_videos_ams
  resources :jeux_videos_jv_plus
  resources :jeux_videos_jvs
  resources :jeux_videos_manga_plus
  resources :jeux_videos_mangas
  resources :jeux_videos_ln_plus
  resources :jeux_videos_lns
  resources :jeux_videos_anime_plus
  resources :jeux_videos_animes
  resources :jeux_videos_actualite_minis
  resources :jeux_videos_actualites
  resources :jeux_videos_groupes
  resources :jeux_videos_staff_people
  resources :jeux_videos_staff_roles
  resources :jeux_videos_staff_societes
  resources :jeux_videos_staff_societe_roles
  resources :jeux_videos_genres
  resources :jeux_videos_themes
  resources :jeux_videos_etats
  resources :jeux_videos_pays
  resources :jeux_videos_pays_dates
  resources :jeux_videos_plateformes
  resources :generiques
  resources :generiques_generics
  resources :generiques_staff_people
  resources :generiques_staff_roles
  resources :generiques_types
  resources :generiques_id_animes
  resources :generique_de_jeu_videos
  resources :generique_de_jeu_videos_jv_generics
  resources :generique_de_jeu_videos_jvs
  resources :generique_de_jeu_videos_staff_people
  resources :generique_de_jeu_videos_staff_roles
  resources :generique_de_jeu_videos_types
  resources :films_asiatiques
  resources :films_asiatiques_artbooks
  resources :films_asiatiques_dvds
  resources :films_asiatiques_concours
  resources :films_asiatiques_quizzs
  resources :films_asiatiques_sondages
  resources :films_asiatiques_cds
  resources :films_asiatiques_doujins
  resources :films_asiatiques_osts
  resources :films_asiatiques_actualite_minis
  resources :films_asiatiques_emission_tv_plus
  resources :films_asiatiques_emission_tvs
  resources :films_asiatiques_cultures
  resources :films_asiatiques_actualites
  resources :films_asiatiques_litterature_asiatique_plus
  resources :films_asiatiques_litterature_asiatiques
  resources :films_asiatiques_people
  resources :films_asiatiques_univers
  resources :films_asiatiques_cinemas
  resources :films_asiatiques_am_plus
  resources :films_asiatiques_ams
  resources :films_asiatiques_jv_plus
  resources :films_asiatiques_jvs
  resources :films_asiatiques_drama_plus
  resources :films_asiatiques_dramas
  resources :films_asiatiques_manga_plus
  resources :films_asiatiques_mangas

app/models/_films_asiatiques_editeurs_vf_role.rb
class FilmsAsiatiquesEditeursVfRole < ApplicationRecord
self.table_name = "_films_asiatiques_editeurs_vf_roles"
end

app/controllers/_films_asiatiques_editeurs_vf_roles_controller.rb
class FilmsAsiatiquesEditeursVfRolesController < ApplicationController
  before_action :set__films_asiatiques_editeurs_vf_role, only: %i[ show edit update destroy ]

  # GET /_films_asiatiques_editeurs_vf_roles or /_films_asiatiques_editeurs_vf_roles.json
  def index
    @_films_asiatiques_editeurs_vf_roles = FilmsAsiatiquesEditeursVfRole.all
  end

  # GET /_films_asiatiques_editeurs_vf_roles/1 or /_films_asiatiques_editeurs_vf_roles/1.json
  def show
  end

  # GET /_films_asiatiques_editeurs_vf_roles/new
  def new
    @_films_asiatiques_editeurs_vf_role = FilmsAsiatiquesEditeursVfRole.new
  end

  # GET /_films_asiatiques_editeurs_vf_roles/1/edit
  def edit
  end

  # POST /_films_asiatiques_editeurs_vf_roles or /_films_asiatiques_editeurs_vf_roles.json
  def create
    @_films_asiatiques_editeurs_vf_role = FilmsAsiatiquesEditeursVfRole.new(_films_asiatiques_editeurs_vf_role_params)

    respond_to do |format|
      if @_films_asiatiques_editeurs_vf_role.save
        format.html { redirect_to _films_asiatiques_editeurs_vf_role_url(@_films_asiatiques_editeurs_vf_role), notice: "Films asiatiques editeurs vf role was successfully created." }
        format.json { render :show, status: :created, location: @_films_asiatiques_editeurs_vf_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @_films_asiatiques_editeurs_vf_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /_films_asiatiques_editeurs_vf_roles/1 or /_films_asiatiques_editeurs_vf_roles/1.json
  def update
    respond_to do |format|
      if @_films_asiatiques_editeurs_vf_role.update(_films_asiatiques_editeurs_vf_role_params)
        format.html { redirect_to _films_asiatiques_editeurs_vf_role_url(@_films_asiatiques_editeurs_vf_role), notice: "Films asiatiques editeurs vf role was successfully updated." }
        format.json { render :show, status: :ok, location: @_films_asiatiques_editeurs_vf_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @_films_asiatiques_editeurs_vf_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /_films_asiatiques_editeurs_vf_roles/1 or /_films_asiatiques_editeurs_vf_roles/1.json
  def destroy
    @_films_asiatiques_editeurs_vf_role.destroy!

    respond_to do |format|
      format.html { redirect_to _films_asiatiques_editeurs_vf_roles_url, notice: "Films asiatiques editeurs vf role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set__films_asiatiques_editeurs_vf_role
      @_films_asiatiques_editeurs_vf_role = FilmsAsiatiquesEditeursVfRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def _films_asiatiques_editeurs_vf_role_params
      params.require(:_films_asiatiques_editeurs_vf_role).permit(:name)
    end
end

app/controllers/films_asiatiques_editeurs_vf_roles_controller.rb
class FilmsAsiatiquesEditeursVfRolesController < ApplicationController
  before_action :set__films_asiatiques_editeurs_vf_role, only: %i[ show edit update destroy ]

  # GET /_films_asiatiques_editeurs_vf_roles or /_films_asiatiques_editeurs_vf_roles.json
  def index
    @_films_asiatiques_editeurs_vf_roles = FilmsAsiatiquesEditeursVfRole.all
  end

  # GET /_films_asiatiques_editeurs_vf_roles/1 or /_films_asiatiques_editeurs_vf_roles/1.json
  def show
  end

  # GET /_films_asiatiques_editeurs_vf_roles/new
  def new
    @_films_asiatiques_editeurs_vf_role = FilmsAsiatiquesEditeursVfRole.new
  end

  # GET /_films_asiatiques_editeurs_vf_roles/1/edit
  def edit
  end

  # POST /_films_asiatiques_editeurs_vf_roles or /_films_asiatiques_editeurs_vf_roles.json
  def create
    @_films_asiatiques_editeurs_vf_role = FilmsAsiatiquesEditeursVfRole.new(_films_asiatiques_editeurs_vf_role_params)

    respond_to do |format|
      if @_films_asiatiques_editeurs_vf_role.save
        format.html { redirect_to films_asiatiques_editeurs_vf_role_url(@_films_asiatiques_editeurs_vf_role), notice: "Films asiatiques editeurs vf role was successfully created." }
        format.json { render :show, status: :created, location: @_films_asiatiques_editeurs_vf_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @_films_asiatiques_editeurs_vf_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /_films_asiatiques_editeurs_vf_roles/1 or /_films_asiatiques_editeurs_vf_roles/1.json
  def update
    respond_to do |format|
      if @_films_asiatiques_editeurs_vf_role.update(_films_asiatiques_editeurs_vf_role_params)
        format.html { redirect_to films_asiatiques_editeurs_vf_role_url(@_films_asiatiques_editeurs_vf_role), notice: "Films asiatiques editeurs vf role was successfully updated." }
        format.json { render :show, status: :ok, location: @_films_asiatiques_editeurs_vf_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @_films_asiatiques_editeurs_vf_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /_films_asiatiques_editeurs_vf_roles/1 or /_films_asiatiques_editeurs_vf_roles/1.json
  def destroy
    @_films_asiatiques_editeurs_vf_role.destroy!

    respond_to do |format|
      format.html { redirect_to films_asiatiques_editeurs_vf_roles_url, notice: "Films asiatiques editeurs vf role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set__films_asiatiques_editeurs_vf_role
      @_films_asiatiques_editeurs_vf_role = FilmsAsiatiquesEditeursVfRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def _films_asiatiques_editeurs_vf_role_params
      params.require(:films_asiatiques_editeurs_vf_role).permit(:name)
    end
end

app/helpers/_films_asiatiques_editeurs_vf_roles_helper.rb
module FilmsAsiatiquesEditeursVfRolesHelper
end

app/views/films_asiatiques_editeurs_vf_roles/_films_asiatiques_editeurs_vf_role.html.erb
<div id="<%= dom_id films_asiatiques_editeurs_vf_role %>">































































  <p>































































    <strong>Name:</strong>































































    <%= films_asiatiques_editeurs_vf_role.name %>































































  </p>































































































































</div>

app/views/films_asiatiques_editeurs_vf_roles/_form.html.erb
<%= form_with(model: _films_asiatiques_editeurs_vf_role) do |form| %>































































  <% if _films_asiatiques_editeurs_vf_role.errors.any? %>































































    <div style="color: red">































































      <h2><%= pluralize(_films_asiatiques_editeurs_vf_role.errors.count, "error") %> prohibited this _films_asiatiques_editeurs_vf_role from being saved:</h2>































































































































      <ul>































































        <% _films_asiatiques_editeurs_vf_role.errors.each do |error| %>































































          <li><%= error.full_message %></li>































































        <% end %>































































      </ul>































































    </div>































































  <% end %>































































































































  <div>































































    <%= form.label :name, style: "display: block" %>































































    <%= form.text_field :name %>































































  </div>































































































































  <div>































































    <%= form.submit %>































































  </div>































































<% end %>

app/views/films_asiatiques_editeurs_vf_roles/edit.html.erb
<h1>Editing films asiatiques editeurs vf role</h1>































































































































<%= render "form", _films_asiatiques_editeurs_vf_role: @_films_asiatiques_editeurs_vf_role %>































































































































<br>































































































































<div>































































  <%= link_to "Show this films asiatiques editeurs vf role", @_films_asiatiques_editeurs_vf_role %> |































































  <%= link_to "Back to films asiatiques editeurs vf roles", films_asiatiques_editeurs_vf_roles_path %>































































</div>

app/views/films_asiatiques_editeurs_vf_roles/index.html.erb
<h1>voir tous les Films Asiatiques Editeurs Vf Roles</h1>
<%@_films_asiatiques_editeurs_vf_roles.each do |x|%>
<%=render x%>
<%end%>
<p>
<%=link_to "nouveau  Films Asiatiques Editeurs Vf Roles", new_films_asiatiques_editeurs_vf_role_path%>
</p>

app/views/films_asiatiques_editeurs_vf_roles/new.html.erb
<h1>New films asiatiques editeurs vf role</h1>































































































































<%= render "form", _films_asiatiques_editeurs_vf_role: @_films_asiatiques_editeurs_vf_role %>































































































































<br>































































































































<div>































































  <%= link_to "Back to films asiatiques editeurs vf roles", films_asiatiques_editeurs_vf_roles_path %>































































</div>

app/views/films_asiatiques_editeurs_vf_roles/show.html.erb
<p style="color: green"><%= notice %></p>































































































































<%= render @_films_asiatiques_editeurs_vf_role %>































































































































<div>































































  <%= link_to "Edit this films asiatiques editeurs vf role", edit_films_asiatiques_editeurs_vf_role_path(@_films_asiatiques_editeurs_vf_role) %> |































































  <%= link_to "Back to films asiatiques editeurs vf roles", films_asiatiques_editeurs_vf_roles_path %>































































































































  <%= button_to "Destroy this films asiatiques editeurs vf role", @_films_asiatiques_editeurs_vf_role, method: :delete %>































































</div>